image_processor:
  ros__parameters:
    camera_frame: "camera_link"
    h_min: 30
    h_max: 90
    s_min: 100
    s_max: 255
    v_min: 100
    v_max: 255
    min_radius: 20
    processing_scale: 0.5
