<?xml version="1.0"?>
<robot name="vision_tracking_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 基础参数 -->
  <xacro:property name="base_length" value="0.4" />       <!-- 底盘长度 -->
  <xacro:property name="base_width" value="0.3" />        <!-- 底盘宽度 -->
  <xacro:property name="base_height" value="0.15" />      <!-- 底盘高度 -->
  <xacro:property name="wheel_radius" value="0.08" />     <!-- 轮子半径 -->
  <xacro:property name="wheel_width" value="0.04" />      <!-- 轮子宽度（轴向长度） -->
  <xacro:property name="wheel_y_offset" value="0.07" />   <!-- 轮子y方向偏移（调整为底盘宽度的一半减去轮子半径） -->
  <xacro:property name="camera_x_offset" value="0.2" />   <!-- 摄像头x方向偏移 -->
  <xacro:property name="camera_z_offset" value="0.1" />   <!-- 摄像头z方向高度 -->
  <xacro:property name="caster_radius" value="0.03" />    <!-- 支撑轮半径 -->
  <xacro:property name="caster_x_offset" value="${base_length/2 - caster_radius}" />  <!-- 支撑轮x方向位置（确保在底盘范围内） -->

  <!-- 机器人底盘 -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.3 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.043" ixy="0.0" ixz="0.0"  
              iyy="0.058" iyz="0.0" izz="0.043"/> 
    </inertial>
  </link>

  <!-- 左轮 -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
              iyy="0.00128" iyz="0.0" izz="0.0001"/>  
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <!-- 调整y偏移量为0.07（底盘半宽0.15 - 轮子半径0.08 = 0.07），确保轮子在底盘范围内 -->
    <origin xyz="0.0 ${wheel_y_offset} -${base_height/2}" rpy="0 1.5708 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- 右轮 -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <!-- 调整y偏移量同上 -->
    <origin xyz="0.0 -${wheel_y_offset} -${base_height/2}" rpy="0 1.5708 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- 前支撑轮（调整为在底盘x范围内） -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <!-- 支撑轮x坐标调整为底盘半长减去支撑轮半径，确保在底盘范围内 -->
    <origin xyz="${caster_x_offset} 0.0 -${base_height/2}"/>
  </joint>

  <!-- 摄像头 -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${camera_x_offset} 0.0 ${camera_z_offset}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo插件 - 差速驱动控制器 -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${2 * wheel_y_offset}</wheel_separation>  <!-- 轮距=2*轮子y偏移 -->
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>       <!-- 轮径=2*轮子半径 -->
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
    </plugin>
  </gazebo>

  <!-- Gazebo插件 - 摄像头 -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera_sensor">
      <update_rate>30.0</update_rate>
      <camera name="camera">
        <horizontal_fov>1.0472</horizontal_fov> <!-- 60 degrees -->
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>10.0</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/camera</namespace>
        </ros>
        <camera_name>camera</camera_name>
        <frame_name>camera_link</frame_name>
        <hack_baseline>0.0</hack_baseline>
      </plugin>
    </sensor>
  </gazebo>

</robot>